sudo: required
services:
  - docker
language: bash
script:
  # Build image
  - docker build -t organizrtools/organizr-v2 .
  # Test image
  - docker run organizrtools/organizr-v2 curl localhost | grep Organizr
after_success:
  # Push image if not a PR
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" ${DOCKER_REGISTRY}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push organizrtools/organizr-v2; fi'
